#!/usr/bin/env python3
"""Process a GPX track into a compact route.js for the static site."""
import math
import re
import json
import sys

import glob
SRC = sorted(glob.glob("/home/frank/Downloads/Odenwald*Diplom*.gpx"))[0]
DST = "assets/route.js"
MIN_STEP_M = 40.0        # keep one point every ~40 m
ELE_NOISE_M = 2.0        # elevation gain threshold to suppress GPS noise

def haversine(lat1, lon1, lat2, lon2):
    R = 6371000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp/2)**2 + math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2 * R * math.asin(math.sqrt(a))

pts = []
with open(SRC, encoding="utf-8") as f:
    lat = lon = ele = None
    for line in f:
        m = re.search(r'<trkpt lat="([-\d.]+)" lon="([-\d.]+)"', line)
        if m:
            lat, lon = float(m.group(1)), float(m.group(2))
        m = re.search(r'<ele>([-\d.]+)</ele>', line)
        if m and lat is not None:
            ele = float(m.group(1))
            pts.append((lat, lon, ele))
            lat = lon = ele = None

print(f"parsed {len(pts)} track points")

# distance, gain, decimation
route = []          # [cumulative_km, lat, lon, ele]
dist = 0.0
gain = 0.0
last_ele = None
last_kept_d = -1e9
max_ele = -1e9
min_ele = 1e9
prev = None
for lat, lon, ele in pts:
    if prev is not None:
        d = haversine(prev[0], prev[1], lat, lon)
        dist += d
        if last_ele is not None:
            de = ele - last_ele
            if abs(de) >= ELE_NOISE_M:
                gain += max(0.0, de)
                last_ele = ele
        elif last_ele is None:
            last_ele = ele
    if prev is None or dist - last_kept_d >= MIN_STEP_M:
        route.append([round(dist/1000, 2), round(lat, 5), round(lon, 5), round(ele, 1)])
        last_kept_d = dist
        max_ele = max(max_ele, ele)
        min_ele = min(min_ele, ele)
    prev = (lat, lon)

km = dist / 1000.0
stats = {
    "km": round(km),
    "gain": round(gain / 10) * 10,
    "maxEle": round(max_ele),
    "minEle": round(min_ele),
    "date": "03.10.2026",
    "name": "Odenwald-Diplom",
}
print(json.dumps(stats), f"kept {len(route)} points")

with open(DST, "w", encoding="utf-8") as f:
    f.write("// generated by tools/process_gpx.py — do not edit\n")
    f.write("window.ROUTE_STATS = " + json.dumps(stats) + ";\n")
    f.write("window.ROUTE = " + json.dumps(route, separators=(",", ":")) + ";\n")
